joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

scaled_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  constraints:
    goal_time: 0.0  # ✅ ĐẶT = 0 để BỎ TIMEOUT!
    stopped_velocity_tolerance: 0.2
    shoulder_pan_joint: {trajectory: 0.3, goal: 0.3}
    shoulder_lift_joint: {trajectory: 0.3, goal: 0.3}
    elbow_joint: {trajectory: 0.3, goal: 0.3}
    wrist_1_joint: {trajectory: 0.3, goal: 0.3}
    wrist_2_joint: {trajectory: 0.3, goal: 0.3}
    wrist_3_joint: {trajectory: 0.3, goal: 0.3}

  state_publish_rate: 500
  action_monitor_rate: 10

# PID GAINS
gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint:
      p: 1000.0
      i: 10.0
      d: 100.0
    shoulder_lift_joint:
      p: 1000.0
      i: 10.0
      d: 100.0
    elbow_joint:
      p: 1000.0
      i: 10.0
      d: 100.0
    wrist_1_joint:
      p: 500.0
      i: 5.0
      d: 50.0
    wrist_2_joint:
      p: 500.0
      i: 5.0
      d: 50.0
    wrist_3_joint:
      p: 500.0
      i: 5.0
      d: 50.0
